/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CheckBoxField: typeof import('./components/formulario/fields/CheckBoxField.vue')['default']
    CompletedForms: typeof import('./components/completed_forms/completedForms.vue')['default']
    DateField: typeof import('./components/formulario/fields/DateField.vue')['default']
    DynamicForm: typeof import('./components/formulario/DynamicForm.vue')['default']
    FormBuilder: typeof import('./components/form_builder/formBuilder.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NumberField: typeof import('./components/formulario/fields/NumberField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./components/formulario/fields/SelectField.vue')['default']
    TextField: typeof import('./components/formulario/fields/TextField.vue')['default']
    TopMenu: typeof import('./components/top_menu/topMenu.vue')['default']
  }
}
